version: "3.9"

services:
  api:
    container_name: resume-api
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - valkey
    env_file:
      - .env
    environment:
      - VALKEY_HOST=valkey
      - VALKEY_PORT=6379
      - CACHE_TTL=86400
    command: uvicorn main:app --host 0.0.0.0 --port 5000
    restart: always

  valkey:
    image: valkey/valkey:latest
    container_name: valkey
    ports:
      - "6379:6379"
    restart: always