import streamlit as st
import requests
import os

try:
    API_URL = st.secrets["API_URL"]
except:
    API_URL = os.getenv("API_URL", "http://localhost:5000")

st.set_page_config(
    page_title="AI Resume Screener",
    layout="centered"
)

# ======================================================
# UI HEADER
# ======================================================

st.title("🤖 AI Resume Screener")
st.caption("FastAPI + Redis/Valkey + Groq")

st.markdown(
    """
Upload a **resume PDF** and paste the **job description**.
The system evaluates the candidate using a local LLM with caching.
"""
)

try:
    health = requests.get(f"{API_URL}/health", timeout=10)
except:
    health = None
    
if health and health.status_code == 200:
    st.sidebar.success("Backend Connected")
else:
    st.sidebar.error("Backend Offline")

# ======================================================
# INPUTS
# ======================================================

resume_file = st.file_uploader(
    "📄 Upload Resume (PDF only)",
    type=["pdf"]
)

job_description = st.text_area(
    "🧾 Job Description",
    height=260,
    placeholder="Paste the full job description here..."
)

# ======================================================
# ACTION
# ======================================================

if st.button("🔍 Screen Resume"):
    if not resume_file or not job_description.strip():
        st.error("Please upload a resume and provide a job description.")
    else:
        with st.spinner("Analyzing resume..."):
            try:
                response = requests.post(
                    f"{API_URL}/screen",
                    files={"resume": resume_file},
                    data={"job_description": job_description},
                    timeout=600
                )

                if response.status_code != 200:
                    st.error(f"API Error: {response.text}")
                else:
                    result = response.json()

                    # ======================================================
                    # RESULTS
                    # ======================================================

                    cache_status = result.get("cache", "UNKNOWN")
                    if cache_status == "HIT":
                        st.success("⚡ Result served from cache")
                    else:
                        st.info("🧠 Result generated by LLM")

                    st.metric(
                        label="Match Score",
                        value=f"{result['match_score']}%"
                    )

                    st.subheader("👤 Candidate")
                    st.write(result.get("candidate_name", "Unknown"))

                    st.subheader("✅ Key Strengths")
                    if result["key_strengths"]:
                        for s in result["key_strengths"]:
                            st.markdown(f"- **{s}**")
                    else:
                        st.write("No major strengths identified.")

                    st.subheader("❌ Missing Critical Skills")
                    if result["missing_critical_skills"]:
                        for m in result["missing_critical_skills"]:
                            st.markdown(f"- {m}")
                    else:
                        st.write("No critical skill gaps detected.")

                    st.subheader("📌 Recommendation")
                    recommendation = result["recommendation"]
                    if recommendation.lower() == "interview":
                        st.success("Interview Recommended")
                    else:
                        st.error("Not Recommended")

                    st.subheader("🧠 Recruiter Reasoning")
                    st.write(result["reasoning"])

            except requests.exceptions.RequestException as e:
                st.error(f"Failed to connect to API: {e}")

# ======================================================
# FOOTER
# ======================================================

st.markdown("---")
st.caption("Built with ❤️ using FastAPI, Groq, Redis/Valkey & Streamlit")
